### PR TITLE
Create JosephusProblem.cpp

### PR DESCRIPTION
**Pull request by shrivardha**
This is my 1st PR. Please do merge it and add hacktober fest label!

### CODE REVIEW

**Comment by Gdsc-Cummins** [comment]
> This is my 1st PR. Please do merge it and add hacktober fest label!

which college ae you from?

**Comment by shrivardha** [comment]
Iit BHU Varanasi

**Comment by shrivardha** [comment]
Please guide me if I have mistaken. I am from IIT BHU Varanasi. Thanks!

**Comment by shrivardha** [comment]
Can I please get to know the reason why it was not merged?

**Pull request closed without merging**
